### ISSUE TITLE
CFP Monsters: Combat Drones lack HD graphics

### ISSUE THREAD

**Issue by Shockwave508** [JoshuaPettus/Marathon-Community-Freeverse-Textures#1]
When using the CFP Monsters with Aleph One v1.8.1, the combat drones lack their proper HD graphics. Scenario is Marathon Infinity.

![20240604213816_1](https://github.com/JoshuaPettus/Marathon-Community-Freeverse-Textures/assets/32436386/56c2118d-b129-4e43-b1bd-813811656448)

**Comment by JoshuaPettus** [comment]
Not all of them are HD (only a few of the monsters that were on someone's hard drive) I can only use what was given to us from freeverse.  For the moment, these are the best quality sprites available. Unfortunately it is what it is.

Drones are probably the worst offenders, but others include the Juggernauts, Enforcers, Player Sprites, Bobs and more I'm probably forgetting.   Perhaps AI upscale might be a good tool to try out, but I'm no expert at that. At some point I'll play around with it.

**Comment by JoshuaPettus** [comment]
Will consider in the future but for the moment not planned

**Comment by JoshuaPettus** [comment]
You will be happy to note I actually found some workable up scaling software called upscayle so I'm giving up-scaling the drones a try.  Definitely a step in the right direction, but I still have to fight with the halo effect around the sprites

**Comment by JoshuaPettus** [comment]
More good news on this front.  I found a download on the Marathon Discord that came from Hippieman himself.  It had an original partial set of the first drone color table. But that's enough for me to remake the other color tables and do away with many of the upscales.  I still need a few to fill out the remaining parts of the set, but it will be in a much better place.

**Comment by JoshuaPettus** [comment]
New Drone sprites have been added along with BoBs, Player and Enforcer.  Will be in the CFP Monster 2.0 release
